### ISSUE TITLE
How to compress a obj file?

### ISSUE THREAD

**Issue by Jonathan1045** [seung-lab/DracoPy#21]
**I want to convert obj file to drc by python,
here is my code**
`def test_decoding_improper_file():
    with open(os.path.join(testdata_directory, "bunny.obj"), "rb") as improper_file:
        file_content = improper_file.read()
        m = DracoPy.decode_buffer_to_mesh(file_content)`
but error
`src\DracoPy.pyx:148: in DracoPy.decode_buffer_to_mesh
    raise_decoding_error(mesh_struct.decode_status)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   raise FileTypeException('Input mesh is not draco encoded')
E   DracoPy.FileTypeException: Input mesh is not draco encoded

src\DracoPy.pyx:137: FileTypeException`
how do I  handle it?

**Comment by william-silversmith** [comment]
Hi Johnathan, 

I think that error is not as helpful as it could be, but the main problem is the mesh is currently in OBJ form which is a text stream describing the mesh. It needs to be decoded into numpy arrays of vertices and faces. Luckily, we provide some libraries that may help (though they support only a subset of the OBJ format).

[zmesh](https://github.com/seung-lab/zmesh) comes with a zmesh.Mesh class that has a `mesh = Mesh.from_obj(txt)` function. We also provide a similar mesh class with more lenient licensing in [cloud-volume](https://github.com/seung-lab/cloud-volume). This will yield a decoded mesh object that has `mesh.vertices` and `mesh.faces`. You can then proceed to use DracoPy. Here's an example:

```python
import zmesh
import DracoPy

with open(os.path.join(testdata_directory, "bunny.obj"), "rt") as improper_file: 
    file_content = improper_file.read() 

mesh = zmesh.Mesh.from_obj(file_content)
draco_binary = DracoPy.encode_mesh_to_buffer(mesh.vertices.flatten('C'), mesh.faces.flatten('C'))
```

**Comment by william-silversmith** [comment]
Arguably, we should have an obj reader in this library too to make this operation easier.

**Comment by Jonathan1045** [comment]
thanks for your reply dude !
I use your example in my project:
```python
drc_file = open("testdata_files/head3d.drc", "wb")
with open("testdata_files/head3d.obj", "rt") as improper_file:
    file_content = improper_file.read()
    mesh = zmesh.Mesh.from_obj(file_content)
    draco_binary = DracoPy.encode_mesh_to_buffer(mesh.vertices.flatten('C'), mesh.faces.flatten('C'))
    drc_file.write(draco_binary)
    drc_file.close()
```
but error
```shell
Traceback (most recent call last):
  File "compressDraco.py", line 33, in <module>
    compress_obj_to_draco()
  File "compressDraco.py", line 27, in compress_obj_to_draco
    mesh = zmesh.Mesh.from_obj(file_content)
  File "C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\zmesh\mesh.py", line 136, in from_obj
    (n1, n2, n3) = re.match(r'vn\s+([-\d\.]+)\s+([-\d\.]+)\s+([-\d\.]+)', line).groups()
AttributeError: 'NoneType' object has no attribute 'groups'

```
How to solve this problem?

**Comment by william-silversmith** [comment]
It seems the regexp I wrote does not match the format of the vertex normals line in your OBJ file. You can try looking at other OBJ parsers that might be more complete (the one I wrote is very simple). Another possibility is that your OBJ file is malformed, but I wouldn't bet on that unless other OBJ parsers fail on it. If you can share the OBJ, I could try it myself and see if the behavior is reasonable.

**Comment by william-silversmith** [comment]
Closing due to inactivity. Let me know if you still need help.
