### ISSUE TITLE
std::vector larger than max_size

### ISSUE THREAD

**Issue by rob-rb** [seung-lab/DracoPy#37]
I get the following Error when I try 
draco.draco_compress(points, faces[:n], colors), whenever n > 23409

Traceback (most recent call last):
  File "/opt/env/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-26-bdfdaacedaea>", line 1, in <module>
    draco.draco_compress(points, faces[:23410], colors)
  File "/opt/project/src/utils/draco.py", line 18, in draco_compress
    binary = DracoPy.encode(
  File "DracoPy.pyx", line 192, in DracoPy.encode
RuntimeError: cannot create std::vector larger than max_size()

**Comment by rob-rb** [comment]
aha sorry I see the problem:
points[faces[23410]]
The output is:
array([[         nan,          nan,          nan],
       [         nan,          nan,          nan],
       [ 84.79447937,   9.83616924, -75.29207611]])
so the problem are the nans!
