### ISSUE TITLE
Installation in a Docker container fails

### ISSUE THREAD

**Issue by ChaiaEran** [seung-lab/DracoPy#49]
I'm trying to install CloudVolume, but DracoPy is a dependency of CloudVolume and it's DracoPy that's giving me the following error on installation with pip:
```
File "/home/node/.local/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 453, in setup
297.6           _check_skbuild_parameters(cmake_install_dir, cmake_source_dir)
297.6         File "/home/node/.local/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 282, in _check_skbuild_parameters
297.6           raise SKBuildError(msg)
297.6
297.6
297.6         setup parameter 'cmake_source_dir' set to a nonexistent directory.
297.6           Project Root  : /tmp/pip-install-81onv6ad/dracopy_b9dd79e7ca6f4185a0ad90e446d45051
297.6           CMake Source Directory: ./draco
```

Here's the relevant parts of my Dockerfile:
```
FROM node-base as python-base

RUN apk add python3 python3-dev py3-pip

FROM python-base as with-build-dependencies
RUN apk add build-base
RUN apk add cmake
RUN apk add zlib-dev

FROM with-build-dependencies as python-requirements

USER node
RUN pip install numpy --break-system-packages
RUN pip install Cython --break-system-packages
RUN pip install scikit-build --break-system-packages
RUN pip install pandas --break-system-packages

RUN pip install -r requirements.txt --break-system-packages
```

**Comment by william-silversmith** [comment]
Generally, whenever someone tries to install from source, they're in for a bad time. 

I tried running the above docker file and got this message on MacOS:

```
failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed```

Is there a reason your installation is not finding one of these wheels?  

https://pypi.org/project/DracoPy/#files

**Comment by ChaiaEran** [comment]
OK, I fixed it by switching from Alpine to Buster.

**Comment by SimonRelu** [comment]
Hey, I'm running in the same issue:

```
23.34 Collecting DracoPy==1.4.0 (from -r /app/requirements.txt (line 34))
23.34   Downloading DracoPy-1.4.0.tar.gz (158 kB)
23.34      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.0/159.0 kB 14.1 MB/s eta 0:00:00
23.34   Preparing metadata (setup.py): started
23.34   Preparing metadata (setup.py): finished with status 'error'
23.34   error: subprocess-exited-with-error
23.34
23.34   × python setup.py egg_info did not run successfully.
23.34   │ exit code: 1
23.34   ╰─> [11 lines of output]
23.34       Traceback (most recent call last):
23.34         File "/usr/local/lib/python3.11/dist-packages/skbuild/setuptools_wrap.py", line 453, in setup
23.34           _check_skbuild_parameters(cmake_install_dir, cmake_source_dir)
23.34         File "/usr/local/lib/python3.11/dist-packages/skbuild/setuptools_wrap.py", line 282, in _check_skbuild_parameters
23.34           raise SKBuildError(msg)
23.34
23.34
23.34         setup parameter 'cmake_source_dir' set to a nonexistent directory.
23.34           Project Root  : /tmp/pip-install-8y7lihlm/dracopy_e2b7517195ea4944b274224bc1f1cbec
23.34           CMake Source Directory: ./draco
23.34
23.34       [end of output]
23.34
23.34   note: This error originates from a subprocess, and is likely not a problem with pip.
23.34 error: metadata-generation-failed
23.34
23.34 × Encountered error while generating package metadata.
23.34 ╰─> See above for output.
23.34
23.34 note: This is an issue with the package mentioned above, not pip.
23.34 hint: See above for details.
23.34
23.34     main()
23.34   File "/app/./relutils/install/install.py", line 118, in main
23.34     install_requirements()
23.34   File "/app/./relutils/install/install.py", line 127, in install_requirements
23.34     _run(
23.34   File "/app/./relutils/install/install.py", line 40, in _run
23.34     raise e
23.34   File "/app/./relutils/install/install.py", line 34, in _run
23.34     out = subprocess.check_output(cmd, shell=True, stderr=subprocess.STDOUT)
23.34           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23.34   File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
23.34     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
23.34            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23.34   File "/usr/lib/python3.11/subprocess.py", line 571, in run
23.35     raise CalledProcessError(retcode, process.args,
23.35 subprocess.CalledProcessError: Command 'pip install -r /app/requirements.txt' returned non-zero exit status 1.
```

I'm running an Ubuntu 20.04 image on macOS 14.3. I have an M1 chip. I don't believe there is a manylinux build for arm64 so that's probably the issue

**Comment by william-silversmith** [comment]
Interesting... it seems I do have aarch64 in the build commands, but I also have musllinux skipped because it takes forever to build. Do you think unskipping musllinux would solve your problem?

**Comment by SimonRelu** [comment]
That's weird because I don't seem to find any aarch64 binaries here: https://pypi.org/project/DracoPy/1.4.0/#files

Also it's not really an issue for me since I can also build my docker with the `--platform linux/amd64` flag and then it uses rosetta to use x86_64 instead of arm64

**Comment by william-silversmith** [comment]
I looked into this a bit more and it's odd, I don't know why those wheels didn't get built. Maybe after I bump the cibuildwheel it's produce them. My other repo that has a very similar Github Action configuration built them. I should give that a try.

**Comment by william-silversmith** [comment]
It looks like the issue is I'm cross compiling for arm64 and Cmake needs an ARM OpenSSL dependency installed.

**Comment by xenolex** [comment]
Hi, are there any updates about this issue?

**Comment by xenolex** [comment]
@william-silversmith please see upper comment

**Comment by william-silversmith** [comment]
I'm currently having trouble rebuilding DracoPy at all. Github actions changed enough that my old build process broke. Hopefully I can release a new version soon...

**Comment by william-silversmith** [comment]
I managed to just upload some aarch64 wheels. Let me know if you need further assistance!
